version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the continuation orb is required in order to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.1.2

parameters:
  e2e_resource_cleanup:
    type: boolean
    default: false
  setup:
    type: boolean
    default: true

executors:
  linux: &linux-e2e-executor
    docker:
      - image: public.ecr.aws/j4f5f3h7/amplify-cli-e2e-base-image-repo-public:latest
    working_directory: ~/repo
    resource_class: large
    environment:
      AMPLIFY_DIR: /home/circleci/repo/out
      AMPLIFY_PATH: /home/circleci/repo/out/amplify-pkg-linux-x64

# our defined job, and its steps
jobs:
  setup:
    executor: 'linux'
    steps:
      - checkout # checkout code
      - run: # run a command
          name: Generate config
          command: |
            cd scripts
            yarn
            yarn split-e2e-tests
      - continuation/continue:
          configuration_path: .circleci/generated_config.yml # use newly generated config to continue
  build:
    parameters:
      os:
        type: executor
        default: linux
    executor: << parameters.os >>
    steps:
      - checkout
      - run: yarn run production-build
      - save_cache:
          key: >-
            amplify-category-api-yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{
            arch }}
          paths:
            - ~/.cache
      - save_cache:
          key: amplify-category-api-ssh-deps-{{ .Branch }}
          paths:
            - ~/.ssh
      - when:
          condition:
            equal:
              - docker:
                  - image: >-
                      public.ecr.aws/j4f5f3h7/amplify-cli-e2e-base-image-repo-public:latest
                working_directory: ~/repo
                resource_class: large
                environment:
                  AMPLIFY_DIR: /home/circleci/repo/out
                  AMPLIFY_PATH: /home/circleci/repo/out/amplify-pkg-linux-x64
              - << parameters.os >>
          steps:
            - persist_to_workspace:
                root: .
                paths: .
  cleanup_resources:
    docker:
      - image: public.ecr.aws/j4f5f3h7/amplify-cli-e2e-base-image-repo-public:latest
    working_directory: ~/repo
    resource_class: large
    environment:
      AMPLIFY_DIR: /home/circleci/repo/out
      AMPLIFY_PATH: /home/circleci/repo/out/amplify-pkg-linux-x64
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          key: >-
            amplify-category-api-yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{
            arch }}
      - run:
          name: Run cleanup script
          command: |
            cd packages/amplify-e2e-tests
            yarn clean-e2e-resources
          no_output_timeout: 90m
      - run:
          name: Scan And Cleanup E2E Test Artifacts
          command: |
            if ! yarn ts-node .circleci/scan_artifacts.ts; then
              echo "Cleaning the repository"
              git clean -fdx
              exit 1
            fi
          when: always
      - store_artifacts:
          path: ~/repo/packages/amplify-e2e-tests/amplify-e2e-reports

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    when: << pipeline.parameters.setup >>
    jobs:
      - setup
  e2e_resource_cleanup:
    when: << pipeline.parameters.e2e_resource_cleanup >>
    jobs:
      - build
      - cleanup_resources:
          context:
            - api-cleanup-resources
            - api-e2e-test-context
          requires:
            - build