import type {
  IAMAuthorizationConfig,
  UserPoolAuthorizationConfig,
  OIDCAuthorizationConfig,
  ApiKeyAuthorizationConfig,
  LambdaAuthorizationConfig,
  AuthorizationModes,
  PartialTranslationBehavior,
  AmplifyGraphqlApiProps,
  AmplifyGraphqlApiResources,
  AmplifyGraphqlApiCfnResources,
  FunctionSlotBase,
  MutationFunctionSlot,
  QueryFunctionSlot,
  SubscriptionFunctionSlot,
  FunctionSlot,
  FunctionSlotOverride,
  ConflictResolution,
  ConflictDetectionType,
  OptimisticConflictResolutionStrategy,
  CustomConflictResolutionStrategy,
  AutomergeConflictResolutionStrategy,
  ConflictResolutionStrategyBase,
  ConflictResolutionStrategy,
  TranslationBehavior,
  IAmplifyGraphqlDefinition,
  IBackendOutputStorageStrategy,
  IBackendOutputEntry,
  AddFunctionProps,
  ModelDataSourceDefinition,
  ModelDataSourceDefinitionStrategy,
  DefaultDynamoDbModelDataSourceDefinitionStrategy,
  AmplifyDynamoDbModelDataSourceDefinitionStrategy,
  ModelDataSourceDefinitionDbType,
} from '@aws-amplify/graphql-api-construct';
import {
  AmplifyDynamoDbTableWrapper,
  TimeToLiveSpecification,
  ProvisionedThroughput,
  SSESpecification,
  SSEType,
  StreamSpecification,
} from '@aws-amplify/graphql-api-construct';

export {
  IAMAuthorizationConfig,
  UserPoolAuthorizationConfig,
  OIDCAuthorizationConfig,
  ApiKeyAuthorizationConfig,
  LambdaAuthorizationConfig,
  AuthorizationModes,
  PartialTranslationBehavior,
  AmplifyGraphqlApiProps,
  AmplifyGraphqlApiResources,
  AmplifyGraphqlApiCfnResources,
  FunctionSlotBase,
  MutationFunctionSlot,
  QueryFunctionSlot,
  SubscriptionFunctionSlot,
  FunctionSlot,
  FunctionSlotOverride,
  ConflictResolution,
  ConflictDetectionType,
  OptimisticConflictResolutionStrategy,
  CustomConflictResolutionStrategy,
  AutomergeConflictResolutionStrategy,
  ConflictResolutionStrategyBase,
  ConflictResolutionStrategy,
  TranslationBehavior,
  IAmplifyGraphqlDefinition,
  IBackendOutputStorageStrategy,
  IBackendOutputEntry,
  AddFunctionProps,
  ModelDataSourceDefinition,
  ModelDataSourceDefinitionStrategy,
  DefaultDynamoDbModelDataSourceDefinitionStrategy,
  AmplifyDynamoDbModelDataSourceDefinitionStrategy,
  ModelDataSourceDefinitionDbType,
  AmplifyDynamoDbTableWrapper,
  TimeToLiveSpecification,
  ProvisionedThroughput,
  SSESpecification,
  SSEType,
  StreamSpecification,
};
export { AmplifyData } from './amplify-data';
export { AmplifyDataDefinition } from './amplify-data-definition';
