import { Flex } from '@aws-amplify/ui-react';
// @ts-ignore - API types are generated by Amplify during test setup
import { Blog, Post } from '../API';
import { createModelHarness } from '../components';
// @ts-ignore - GraphQL operations are generated by Amplify during test setup
import { createBlog, createPost, deleteBlog, deletePost, updateBlog, updatePost } from '../graphql/mutations';
// @ts-ignore - GraphQL operations are generated by Amplify during test setup
import { getBlog, getPost, listBlogs, listPosts } from '../graphql/queries';
// @ts-ignore - GraphQL operations are generated by Amplify during test setup
import { onCreateBlog, onCreatePost, onDeleteBlog, onDeletePost, onUpdateBlog, onUpdatePost } from '../graphql/subscriptions';
import { NavBar } from '../NavBar';

const BlogHarness = createModelHarness<Blog>({
  recordName: 'blog',
  fields: ['title', 'posts'],
  createMutation: createBlog,
  updateMutation: updateBlog,
  deleteMutation: deleteBlog,
  getQuery: getBlog,
  listQuery: listBlogs,
  onCreateSubscription: onCreateBlog,
  onUpdateSubscription: onUpdateBlog,
  onDeleteSubscription: onDeleteBlog,
  sentinelData: {
    title: 'created blog',
    author: 'test suite',
  },
});

const PostHarness = createModelHarness<Post>({
  recordName: 'post',
  fields: ['title', 'blog', 'blogPostsId'],
  createMutation: createPost,
  updateMutation: updatePost,
  deleteMutation: deletePost,
  getQuery: getPost,
  listQuery: listPosts,
  onCreateSubscription: onCreatePost,
  onUpdateSubscription: onUpdatePost,
  onDeleteSubscription: onDeletePost,
  sentinelData: {
    title: 'created post',
    content: 'what a great post',
  },
});

export const Blogs = () => {
  return (
    <Flex direction='column'>
      <NavBar />
      <BlogHarness />
      <PostHarness />
    </Flex>
  );
};
