import { Flex } from '@aws-amplify/ui-react';
// @ts-ignore - API types are generated by Amplify during test setup
import { Todo } from '../API';
import { createModelHarness } from '../components';
// @ts-ignore - GraphQL operations are generated by Amplify during test setup
import { createTodo, updateTodo, deleteTodo } from '../graphql/mutations';
// @ts-ignore - GraphQL operations are generated by Amplify during test setup
import { listTodos, getTodo } from '../graphql/queries';
// @ts-ignore - GraphQL operations are generated by Amplify during test setup
import { onCreateTodo, onDeleteTodo, onUpdateTodo } from '../graphql/subscriptions';
import { NavBar } from '../NavBar';

const TodoHarness = createModelHarness<Todo>({
  recordName: 'todo',
  fields: ['content'],
  createMutation: createTodo,
  updateMutation: updateTodo,
  getQuery: getTodo,
  listQuery: listTodos,
  deleteMutation: deleteTodo,
  onCreateSubscription: onCreateTodo,
  onUpdateSubscription: onUpdateTodo,
  onDeleteSubscription: onDeleteTodo,
  sentinelData: {
    content: 'created todo',
    metadata: {
      targetCompletionDate: '2021-10-13',
      percentChanceOfCompletion: 0.75,
    },
  },
});

export const Todos = () => {
  return (
    <Flex direction='column'>
      <NavBar />
      <TodoHarness />
    </Flex>
  );
};
