/**
 * Represents stack outputs generated by Amplify Auth Construct.
 */
export type AuthConstructStackOutputs = {
  authRegion: string;
  userPoolId: string;
  webClientId: string;
  identityPoolId: string;
};

/**
 * Represents stack outputs generated by AmplifyGraphqlApi Construct and UserPool Construct.
 */
export type UserPoolAuthConstructStackOutputs = {
  awsAppsyncRegion: string;
  awsAppsyncApiEndpoint: string;
  awsAppsyncApiKey: string;
  userPoolId: string;
  webClientId: string;
};
