/**
 * Represents stack outputs generated by Amplify Auth Construct.
 */
export type AuthConstructStackOutputs = {
  authRegion: string;
  userPoolId: string;
  webClientId: string;
  identityPoolId: string;
};
