export type {
  IAMAuthorizationConfig,
  UserPoolAuthorizationConfig,
  OIDCAuthorizationConfig,
  ApiKeyAuthorizationConfig,
  LambdaAuthorizationConfig,
  AuthorizationModes,
  PartialTranslationBehavior,
  AmplifyGraphqlApiProps,
  AmplifyGraphqlApiResources,
  AmplifyGraphqlApiCfnResources,
  FunctionSlotBase,
  MutationFunctionSlot,
  QueryFunctionSlot,
  SubscriptionFunctionSlot,
  FunctionSlot,
  FunctionSlotOverride,
  ConflictResolution,
  ConflictDetectionType,
  OptimisticConflictResolutionStrategy,
  CustomConflictResolutionStrategy,
  AutomergeConflictResolutionStrategy,
  ConflictResolutionStrategyBase,
  ConflictResolutionStrategy,
  TranslationBehavior,
  IAmplifyGraphqlDefinition,
  IBackendOutputStorageStrategy,
  IBackendOutputEntry,
  AddFunctionProps,
} from './types';
export { AmplifyGraphqlApi } from './amplify-graphql-api';
export { AmplifyGraphqlDefinition } from './amplify-graphql-definition';
export {
  AmplifyDynamoDbTableWrapper,
  TimeToLiveSpecification,
  ProvisionedThroughput,
  SSESpecification,
  SSEType,
  StreamSpecification,
} from './amplify-dynamodb-table-wrapper';
