export type {
  IAMAuthorizationConfig,
  UserPoolAuthorizationConfig,
  OIDCAuthorizationConfig,
  ApiKeyAuthorizationConfig,
  LambdaAuthorizationConfig,
  AuthorizationConfig,
  PartialSchemaTranslationBehavior,
  AmplifyApiSchemaPreprocessorOutput,
  AmplifyGraphqlApiProps,
  AmplifyGraphqlApiResources,
  AmplifyGraphqlApiCfnResources,
  FunctionSlotBase,
  MutationFunctionSlot,
  QueryFunctionSlot,
  SubscriptionFunctionSlot,
  FunctionSlot,
  FunctionSlotOverride,
  ConflictResolution,
  ConflictDetectionType,
  OptimisticConflictResolutionStrategy,
  CustomConflictResolutionStrategy,
  AutomergeConflictResolutionStrategy,
  ConflictResolutionStrategyBase,
  ConflictResolutionStrategy,
  SchemaTranslationBehavior,
  IAmplifyGraphqlSchema,
  IBackendOutputStorageStrategy as IGenericBackendOutputStorageStrategy,
  IBackendOutputEntry as IGenericBackendOutputEntry,
} from './types';
export { AmplifyGraphqlApi } from './amplify-graphql-api';
export { AmplifyGraphqlSchema } from './amplify-graphql-schema';
