import {
  AmplifyDynamoDbModelDataSourceStrategy,
  DefaultDynamoDbModelDataSourceStrategy,
  ModelDataSourceDbType,
  ModelDataSourceSqlDbType,
} from './model-datasource-strategy-types';

export const DDB_DB_TYPE: ModelDataSourceDbType = 'DYNAMODB';

export const MYSQL_DB_TYPE: ModelDataSourceSqlDbType = 'MYSQL';

export const POSTGRES_DB_TYPE: ModelDataSourceSqlDbType = 'POSTGRES';

export const DYNAMODB_DEFAULT_TABLE_STRATEGY: DefaultDynamoDbModelDataSourceStrategy = {
  dbType: 'DYNAMODB',
  provisionStrategy: 'DEFAULT',
};

export const DYNAMODB_AMPLIFY_TABLE_STRATEGY: AmplifyDynamoDbModelDataSourceStrategy = {
  dbType: 'DYNAMODB',
  provisionStrategy: 'AMPLIFY_TABLE',
};

/** The name of the SQL ModelDataSourceStrategy created by the CLI import flow. */
export const IMPORTED_SQL_API_STRATEGY_NAME = 'ImportedSQLAPI';

/** The name of the schema file generated by the CLI import flow. */
export const SQL_SCHEMA_FILE_NAME = 'schema.sql.graphql';
