export const TYPESCRIPT_DATA_SCHEMA_CONSTANTS = {
  SCHEMA_PACKAGE: '@aws-amplify/data-schema',
  SCHEMA_PACKAGE_INTERNALS: '@aws-amplify/data-schema/internals',
  BACKEND_PACKAGE: '@aws-amplify/backend',
  MODEL_METHOD: 'model',
  SCHEMA_METHOD: 'schema',
  IDENTIFIER_METHOD: 'identifier',
  ARRAY_METHOD: 'array',
  REQUIRED_METHOD: 'required',
  STRING_METHOD: 'string',
  ENUM_METHOD: 'enum',
  REFERENCE_A: 'a',
  EXPORT_VARIABLE_NAME: 'schema',
  INTERNALS_CONFIGURE_METHOD: 'configure',
  BACKEND_SECRET_METHOD: 'secret',
  PROPERTY_VPC: 'vpcConfig',
  PROPERTY_VPC_ID: 'vpcId',
  PROPERTY_SECURITY_GROUP_IDS: 'securityGroupIds',
  PROPERTY_AZ_CONFIG: 'subnetAvailabilityZones',
  PROPERTY_SUBNET_ID: 'subnetId',
  PROPERTY_AZ: 'availabilityZone',
  PROPERTY_DATABASE: 'database',
  PROPERTY_CONNECTION_URI: 'connectionUri',
  PROPERTY_ENGINE: 'engine',
  PROPERTY_IDENTIFIER: 'identifier',
};
